# Generated by Django 5.0.2 on 2026-02-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hiker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('picture', models.CharField(blank=True, max_length=100000, null=True)),
                ('ability', models.CharField(choices=[('2', 'Casual Stroller'), ('3', 'Average Pace'), ('4', 'On a Mission')], default=2, max_length=30)),
            ],
        ),
    ]
